Text overlay now works in nodeJS
publiclab/image-sequencer pull request #1518
Opened 2020-01-17 14:46 UTC by blurry-x-face

Concerns #1378 

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm test`
* [x] code is in uniquely-named feature branch and has no merge conflicts
* [x] PR is descriptively titled
* [x] ask `@publiclab/is-reviewers` for help, in a comment below
* [x] Insert-step functionality is working correct as expected.
> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software
Please make sure to get at least two reviews before asking for merging the PR as that would make the PR more reliable on our part
Thanks!

2020-01-17 17:39 UTC, harshkhandeparkar requested changes
I think the info.json file for TextOverlay has a `required` field which needs to be removed. This field skips the test for this module.

2020-01-17 17:57 UTC, HarshKhandeparkar commented
Waiting for the tests....

2020-01-19 07:24 UTC, HarshKhandeparkar commented
Please fix the conflicts. Thanks!

2020-01-20 11:11 UTC, blurry-x-face commented
I am having problem in making it work in node, after #1533 Image element is used in TextOverlay, so I imported it from JSDOM but its image.onload is not firing and when I am using ctx.putImageData it is not working with GIFS, @ataata107 do you have any idea? Why did you removed putImageData and used drawImage instead?

2020-01-20 12:07 UTC, blurry-x-face commented
I am facing problem in running it in nodeJS after #1533, It is using Image element, but for some reason when I imported it from jsdom, the onload event is not firing and when I used ctx.putImageData instead of ctx.drawImage, text overlay stopped working for GIfs :confused: @ataata107 Why did you removed putImageData and used drawImage instead is there any major difference?

2020-01-20 13:56 UTC, HarshKhandeparkar commented
Is it not working currently?

2020-01-20 15:04 UTC, blurry-x-face commented
No, it isn't

2020-01-20 15:05 UTC, HarshKhandeparkar commented
#1533 was a dangerous PR. We need to do a followup soon and fix some things.

2020-01-20 15:12 UTC, blurry-x-face commented
Yes! It also broke #1546, It was working fine before #1533, after that it is not resizing the image

2020-01-20 15:15 UTC, HarshKhandeparkar commented
Hmm. Would you like to open an issue for this? Also mention some things which broke.

2020-01-20 15:29 UTC, blurry-x-face commented
Yeah, sure

2020-01-21 19:32 UTC, ataata107 commented
@blurry-x-face I had to do that because putting pixels (of gifs) onto canvas was tampering the data. But instead if I used the source url it worked fine

2020-01-22 20:49 UTC, blurry-x-face commented
Ok, so after A LOT OF DEBUGGING, I finally found the reason why this was having problem running in node, turns out the problem was this
https://github.com/publiclab/image-sequencer/blob/f6d53163b92b8678903956647cddf65b020e0b56/src/modules/_nomodule/PixelManipulation.js#L292
generateOutput was getting called beore the extramanipulation was completed so generateOutput was getting run twice!! one time in pixelManipulation and one time in extramanipulation
https://github.com/publiclab/image-sequencer/blob/f6d53163b92b8678903956647cddf65b020e0b56/src/modules/TextOverlay/Module.js#L15-L17
Therefore in node the output was generated from the first generateOutput call hence the image was not getting changed because the way image is generated from cli is that it generates the image the first time generateOutput is called, so to fix this what we can do is:
```js
if (options.extraManipulation){
  frames[f] = options.extraManipulation(framePix, setRenderState, generateOutput) || framePix; // extraManipulation is used to manipulate each pixel individually.
  perFrameShape = frames[f].shape;
}else
  generateOutput();
```
And then each module that uses extramanipulation we have to call generateOutput after extramanipulation is completed like we do in text-overlay! :weary: 
https://github.com/publiclab/image-sequencer/blob/f6d53163b92b8678903956647cddf65b020e0b56/src/modules/TextOverlay/Module.js#L15-L17
I'll open an issue regarding this and make a PR for it super soon!

2020-01-22 21:18 UTC, blurry-x-face commented
Ok, so after A LOT OF DEBUGGING, I finally found the reason why this was having problem running in node, turns out the problem was this
https://github.com/publiclab/image-sequencer/blob/f6d53163b92b8678903956647cddf65b020e0b56/src/modules/_nomodule/PixelManipulation.js#L292
generateOutput was getting called beore the extramanipulation was completed so generateOutput was getting run twice!! one time in pixelManipulation and one time in extramanipulation
https://github.com/publiclab/image-sequencer/blob/f6d53163b92b8678903956647cddf65b020e0b56/src/modules/TextOverlay/Module.js#L15-L17
Therefore in node the output was generated from the first generateOutput call hence the image was not getting changed because the way image is generated from cli is that it generates the image the first time generateOutput is called, so to fix this what we can do is:
```js
if (options.extraManipulation){
  frames[f] = options.extraManipulation(framePix, setRenderState, generateOutput) || framePix; // extraManipulation is used to manipulate each pixel individually.
  perFrameShape = frames[f].shape;
}else
  generateOutput();
```
And then each module that uses extramanipulation we have to call generateOutput after extramanipulation is completed like we do in text-overlay! :weary: 
https://github.com/publiclab/image-sequencer/blob/f6d53163b92b8678903956647cddf65b020e0b56/src/modules/TextOverlay/Module.js#L15-L17
I'll open an issue regarding this and make a PR for it super soon!

2020-07-08 05:25 UTC, HarshKhandeparkar commented
Needs a small rebase.

2026-07-14 20:11 UTC, closed without merging