Add easy to use interface for draw-rectangle
publiclab/image-sequencer pull request #1590
Opened 2020-01-28 21:38 UTC by blurry-x-face

This PR adds easy to use interface for draw-rectangle

![draw-rect](https://user-images.githubusercontent.com/42492389/73307574-7799d100-4244-11ea-9314-8e4c9dda2f17.gif)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm run test-all`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] ask `@publiclab/is-reviewers` for help, in a comment below
* [ ] Insert-step functionality is working correct as expected.
> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software
Please make sure to get at least two reviews before asking for merging the PR as that would make the PR more reliable on our part
Thanks!

2020-01-28 22:17 UTC, blurry-x-face commented
@publiclab/is-reviewers @jywarren please review this

2020-07-10 18:58 UTC, jywarren commented
Confirmed this works in GitPod! I'll update but do you think you could add an instruction saying "please draw a rectangle by dragging" or something?

![Screen Shot 2020-07-10 at 2 57 37 PM](https://user-images.githubusercontent.com/24359/87188984-cb154e00-c2bd-11ea-9668-c040470875b6.png)
![Screen Shot 2020-07-10 at 2 57 44 PM](https://user-images.githubusercontent.com/24359/87188985-cbade480-c2bd-11ea-85ac-00b990a25a5c.png)

2020-07-12 14:39 UTC, blurry-x-face commented
Hi @jywarren hope you're doing well, I've updated the PR to include the helper text, kindly review it again!

2020-08-04 03:29 UTC, jywarren commented
Nice! Tested and confirmed in GitPod:

![image](https://user-images.githubusercontent.com/24359/89249821-2991cb80-d5e1-11ea-89e3-88170b17b78b.png)

2020-08-04 03:30 UTC, jywarren requested changes
Do you think you could write a simple Jest test for this? It's complex enough that I'd like to protect it with a UI test. Thank you!

2026-07-14 20:09 UTC, closed without merging