added issue templates
publiclab/image-sequencer pull request #1916
Opened 2021-06-26 06:09 UTC by unnati914

Fixes #1757   (<=== Replace `0000` with the Issue Number)

Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. Thanks!

* [ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `npm run test-all`
* [ ] code is in uniquely-named feature branch and has no merge conflicts
* [ ] PR is descriptively titled
* [ ] ask `@publiclab/is-reviewers` for help, in a comment below
* [ ] Insert-step functionality is working correct as expected.
> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail at first!

If tests do fail, click on the red `X` to learn why by reading the logs.

Please be sure you've reviewed our contribution guidelines at https://publiclab.org/contributing-to-public-lab-software
Please make sure to get at least two reviews before asking for merging the PR as that would make the PR more reliable on our part
Thanks!

2021-06-26 14:31 UTC, jywarren approved these changes

2021-06-26 14:33 UTC, harshkhandeparkar reviewed
Why are the files added twice?

2021-06-29 14:11 UTC, jywarren requested changes
Just saw the extra copies, but should be pretty easy to remove them! If you'd like help we're here, too!

Also, if it's possible to add `_` characters instead of spaces into the file names, that would be awesome. Thank you!!

2021-07-01 07:46 UTC, unnati914 commented on enhancement template.md
> +# New Enhancement Request
i don't know how this happened will surely remove this

2021-07-01 07:56 UTC, unnati914 commented on enhancement template.md
> +# New Enhancement Request
done

2021-07-01 15:42 UTC, jywarren approved these changes

2021-07-01 15:42 UTC, jywarren commented
Yay, thank you! This is great.

2021-07-01 15:42 UTC, merged